<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<TargetFramework>net8.0-windows</TargetFramework>
	<OutputType>Exe</OutputType>
	<GenerateManifests>false</GenerateManifests>
  </PropertyGroup>
  <ItemGroup>
	<None Update="Markdown.docx">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
  </ItemGroup>
  <ItemGroup>
	<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
	<PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
	<PackageReference Include="DevExpress.Pdf.Drawing" Version="24.2.*-*" />
        <PackageReference Include="DevExpress.RichEdit.Core" Version="24.2.*-*" />
  </ItemGroup>
</Project>